### ISSUE TITLE
Add additional info to S3 storage docs for broken non-aws scenario after Zammad v6.5

### ISSUE THREAD

**Issue by vanOert** [zammad/zammad-admin-documentation#798]
Related documentation article:
https://admin-docs.zammad.org/en/latest/settings/system/storage.html

Related issue solved by @fliebe92: 
See: https://community.zammad.org/t/backblaze-s3-broken-after-update-to-6-5/17377

**Comment by ralf401** [comment]
Add 

```
  request_checksum_calculation: when_required
  response_checksum_validation: when_required
```
to configuration for non AWS/S3 setup.

Example: 
```
s3:
  access_key_id: 'redacted'
  secret_access_key: 'redacted'
  region: 'eu-central'
  endpoint: 'https://s3.eu-central-003.backblazeb2.com'
  force_path_style: true
  bucket: 'redacted'
  request_checksum_calculation: when_required
  response_checksum_validation: when_required
```
